### ISSUE TITLE
Spring Boot 2.4.x compatibility (update to Spring Cloud Illford)

### ISSUE THREAD

**Issue by benkiefer** [zalando/spring-cloud-config-aws-kms#109]
It looks like the new version of [Spring Cloud (Illford) ](https://spring.io/blog/2020/12/22/spring-cloud-2020-0-0-aka-ilford-is-available) is now generally available which is compatible with Spring Boot 2.4.x.

Opening this issue so that folks can track when support for 2.4.x is added.

Thank you for all of your work on this project.

**Comment by rogervinas** [comment]
@benkiefer can you take a look at https://github.com/zalando/spring-cloud-config-aws-kms/pull/118? thanks!
