### ISSUE TITLE
Any plan to support newer Spring-boot version?

### ISSUE THREAD

**Issue by javiercanillas** [zalando/spring-cloud-config-aws-kms#125]
Do you have any plan to support newer version of Spring-boot? I'm talking about 2.3, 2.4 or even 2.5 version. As far as I have attempted it's not compatible.

It seems `org.springframework.cloud.util.PropertyUtils` was removed or moved somewhere else, Which throws a `java.lang.NoClassDefFoundError` when attempting to start the application.

**Comment by javiercanillas** [comment]
Ok, the problem seems to be that, for some reason, this force to use a lower version of `org.springframework.cloud:spring-cloud-context` so introducing it as an exclusion might work. I will update this post if it finally works.

**Comment by danielrohe** [comment]
released version 3.1.1 that builds on top of AwSpring spring-cloud-aws
