### ISSUE TITLE
ava.lang.NoClassDefFoundError: com/amazonaws/transform/JsonErrorUnmarshallerV2

### ISSUE THREAD

**Issue by jyothri** [zalando/spring-cloud-config-aws-kms#15]
I included the latest version of spring-cloud-config-aws-kms in my application, but getting the NoClassDefFound error.

[stacktrace.txt](https://github.com/zalando/spring-cloud-config-aws-kms/files/791238/stacktrace.txt) & [full dependency tree](https://github.com/zalando/spring-cloud-config-aws-kms/files/791239/dependency_tree.txt)

I downgraded the version of aws-java-sdk-core to 1.10.40

	  <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk-core</artifactId>
        <version>1.10.40</version>
      </dependency>

but getting the below error - 
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.s3.AmazonS3Client

It seems the latest versions have some incompatibility. Could someone provide any inputs.

**Comment by harti2006** [comment]
It looks like the project is using an old java sdk (1.10.*). I will try to upgrade dependencies.

**Comment by harti2006** [comment]
@jyothri Hi, I created a new version 1.6 and upgraded all the dependencies to use some recent values(see #16). It should be available in maven central soon. 

Please tell me if this works out for you.

**Comment by jyothri** [comment]
@harti2006 Thanks for the quick turnaround. I'll check it out and update the thread!

**Comment by jyothri** [comment]
The newest version works for me. Thanks!

**Comment by haibbi** [comment]
tyu
