### ISSUE TITLE
Create current releases in Github

### ISSUE THREAD

**Issue by mariodavid** [zalando/spring-cloud-config-aws-kms#26]
Hi,

when I want to use the library, i looked at this page:
https://github.com/zalando/spring-cloud-config-aws-kms/releases

It states that the latest release is 1.4. As it turns out when looking at https://github.com/zalando/spring-cloud-config-aws-kms/tags there are already takes to releases up to 1.7 (http://repo1.maven.org/maven2/org/zalando/spring-cloud-config-aws-kms/1.7/).

It would be great if you could add those Github releases.

Thanks for the very neat lib...

Bye
Mario

**Comment by harti2006** [comment]
Hi Mario, thanks for the hint. I missed it the last times, but will add some description this week.

**Comment by harti2006** [comment]
I added the missing the missing [release descriptions](https://github.com/zalando/spring-cloud-config-aws-kms/releases).

Additionally I did some cleanup, which leads to a new major version [2.0-beta1](https://github.com/zalando/spring-cloud-config-aws-kms/releases/tag/2.0-beta1).
Would be great, if you you could try it out in your project and give me some feedback on PR #27  whether it works for you or not ;-)
