### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by LappleApple** [zalando/spring-cloud-config-aws-kms#4]
This looks useful to non-Zalandos but hasn't been worked on in a while. What is its future?

**Comment by harti2006** [comment]
Not sure if anybody uses it. I guess most teams are doing KMS encryption/decryption with Taupage AMI's built-in feature. So they don't need to care about that within their applications.

However, this small library / extension is basically feature-complete. Of course it can be that the interface changes in future Spring Cloud Config versions, but until then, there is no additional work necessary.

**Comment by LappleApple** [comment]
@harti2006 Thanks for this feedback of a while back. Some suggestions (I'm offering help here): 1. ask the team who's using it; 2. update README; 3. ask the Open Source Guild for project feedback; 4. consider feedback; proceed with next step. Sound good?

**Comment by harti2006** [comment]
@LappleApple yes, that sounds good to me.
