### ISSUE TITLE
Having trouble using decrypted AWS KMS data key

### ISSUE THREAD

**Issue by jslott** [zalando/spring-cloud-config-aws-kms#44]
I created an aws data key, for example: RUJC+kFHFWMHYKGOJrB0Nf/J1PsCaHFPEFwdMtaXymc=. If you base64 decode this into byte[] you can see it's length is 32 and can be used by AES as key. (i.e. Java's SecretKeySpec).

However, when I have your library decrypt my cipher text blob, which does a new String(bytes) on what is returned by the AWS SDK (KmsTextEncryptor, line 136), the byte length is now 50 and not suitable as a key.

```
String key = "RUJC+kFHFWMHYKGOJrB0Nf/J1PsCaHFPEFwdMtaXymc=";
byte[] bytes = Base64.getDecoder().decode(key);
System.out.println("len = " + bytes.length);
byte[] bytes2 = new String(bytes).getBytes();
System.out.println("len2 = " + bytes2.length);
```
When I generate my own random 32-byte length key (using entirely printable chars) instead of using aws data key, your library works fine.

**Comment by jslott** [comment]
Here's what I wound up doing.

1. Generate a data key using `aws kms generate-data-key --key-id <key id> ...`. Disregard the ciphertext, and just hold onto the (base64 encoded) plaintext
2. Re-encrypt the (base64 encoded) plaintext from step 1 using `aws kms encrypt` and put the cipher text (base64) into my application.yml
3. The bound value is really the base64 encoded value of my secret key into AES.

**Comment by harti2006** [comment]
Hi @jslott, thanks for filing this issue. I'm going to have a look at it.

**Comment by harti2006** [comment]
Ok, I was able to reproduce the issue. Indeed the decrypted ciphertext differs from the initial plaintext. The question is: Since the library is implementing the interface `TextEncryptor` which only deals with Strings and not with byte arrays, I'm not sure how to represent those unprintable chars in the final String.
I could offer you to refactor the code and make the encryption / decryption methods available with with some `byte[]` or `ByteBuffer` interface. This would at least allow you to re-use the code. What do you think, @jslott ?

**Comment by harti2006** [comment]
Other idea: some extra feature to leave the output Base64 encoded.

application.yaml
```
secretPassword: "{cipher}[output=base64]CiA47hYvQqWFFGq3TLtzQO5FwZMam2AnaeQt...
```

Then you have take care on your own to decode it.

**Comment by jslott** [comment]
Yeah, I think `[output=base64]` is a good idea. I have a quick and dirty fix, but i'm not allowed to push branches to your repo.

**Comment by harti2006** [comment]
Ok, I got you added as collaborator. Please push your fix and I will try to incorporate it into the final solution.

**Comment by jslott** [comment]
There you go. My stuff is kinda quick & dirty. Happy for either you or me to make changes as you direct.

https://github.com/zalando/spring-cloud-config-aws-kms/tree/base64-output-encoding

**Comment by harti2006** [comment]
Ok @jslott I picked up some ideas from your branch and noticed that the code is quite similar to the encryption context feature (parsing a map). I refactored everything and created a pull request: https://github.com/zalando/spring-cloud-config-aws-kms/pull/45

**Comment by harti2006** [comment]
The feature is release in versions `2.1` (Spring Boot 1.5) and `3.1` (Spring Boot 2.0).
