### ISSUE TITLE
kms proxy for localhost

### ISSUE THREAD

**Issue by eskuai** [zalando/spring-cloud-config-aws-kms#47]
Hi

how can i config http proxy for local profile?

**Comment by harti2006** [comment]
Hi @eskuai. If you need to send KMS requests through some proxy in your local environment, you can just create your own custom Spring bean of type `AWSKMS` and apply your desired client configuration:

```java
import com.amazonaws.ClientConfiguration;
import com.amazonaws.ProxyAuthenticationMethod;
import com.amazonaws.services.kms.AWSKMS;
import com.amazonaws.services.kms.AWSKMSClient;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;

import java.util.Arrays;

@Configuration
@Profile("local")
class CustomLocalKMSConfig {

    @Bean
    AWSKMS myAwsKms() {
        return AWSKMSClient.builder()
                .withClientConfiguration(new ClientConfiguration()
                        .withProxyAuthenticationMethods(Arrays.asList(ProxyAuthenticationMethod.KERBEROS, ProxyAuthenticationMethod.BASIC))
                        .withProxyDomain("foo")
                        .withProxyHost("foo")
                        .withProxyPort(12345)
                        .withProxyUsername("hello")
                        .withProxyPassword("world")
                        .withProxyWorkstation("foo"))
                .build();
    }
}
```

Just run your application with property `--spring.profiles.active=local` to activate this configuration. Please note that this approach will ignore the settings of `aws.kms.endpoint` and `aws.kms.region` and instead use the SDK default unless you configure them manually with the KmsClientBuilder.

**Comment by eskuai** [comment]
Hello,
Thank you so much.  Right, i'll test
if i use, into bootstramp.properties 
aws.kms.keyId
aws.kms.region

is it working?

does anyone  got the problem that use proxies into production environment?
i think could be useful to set proxy params into config process
tx

**Comment by harti2006** [comment]
> if i use, into bootstramp.properties
> aws.kms.keyId
> aws.kms.region

`aws.kms.keyId` will work as it is unrelated to the client config.
`aws.kms.region` won't work.  Just add `.withRegion(Regions.EU_CENTRAL_1)` to your bean definition, or (even better) omit it and rely on the [default region provider chain](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html#automatically-determine-the-aws-region-from-the-environment)

For exactly such use cases it is possible to provide a custom `AWSKMS` bean to the library. I would rather not try to make every single piece of client config available in application.yaml. Spring Cloud AWS also does not do that. I would like this lib to stay small and easily maintainable.

**Comment by eskuai** [comment]
I've config a secret password to access to aurora into application properties.
test={cipher}AQICAHizgKM/qrvTuBIhZrHW24BAbZ248vrnRbi8qmr6JFa2rw@Configuration

Then, if i settting on main 
main()
		 System.setProperty("http.proxyHost", "proxy.proxy");
		System.setProperty("http.proxyPort", "8080");
		
		 System.setProperty("https.proxyHost", "proxy.proxy");
		 System.setProperty("https.proxyPort", "8080");
app.run();

it is works ok...

but if i remove before config and 
@Profile("local")
public class CustomLocalKMSConfig {

	@Autowired
	Environment env;

	@Value("${amazon.aws.accesskey}")
	private String awsId;

	@Value("${amazon.aws.secretkey}")
	private String awsKey;

	@Value("${s3.region}")
	private String region;

	@Bean
	AWSKMS localAwsKms() {

		ClientConfiguration clientCfg = new ClientConfiguration();
		clientCfg.setProtocol(Protocol.HTTPS);
		clientCfg.setClientExecutionTimeout(10 * 60 * 1000);
		clientCfg.setRequestTimeout(5 * 60 * 1000);
		clientCfg.setMaxErrorRetry(5);
		clientCfg.setUseTcpKeepAlive(true);
		clientCfg.setUseThrottleRetries(true);
		clientCfg.withMaxConnections(20);
		clientCfg.setProxyHost("proxy.proxy");
		clientCfg.setProxyPort(8080);

		BasicAWSCredentials awsCreds = new BasicAWSCredentials(awsId, awsKey);
		return AWSKMSClientBuilder.standard().withRegion(Regions.fromName(region))
				.withCredentials(new AWSStaticCredentialsProvider(awsCreds)).withClientConfiguration(clientCfg).build();

	}
}

And profile is active local... not working ... 
Connect to kms.eu-west-1.amazonaws.com:443 [kms.eu-west-1.amazonaws.com/54.239.32.132] failed: connect timed out

because i dont need to use a explicit kms client ...

**Comment by eskuai** [comment]
Thank you so much.
