### ISSUE TITLE
Any plans to update to springboot 1.4?

### ISSUE THREAD

**Issue by dimiro1** [zalando/spring-cloud-config-aws-kms#5]

**Comment by hjacobs** [comment]
@jbellmann there should not be any issue upgrading, right?

**Comment by harti2006** [comment]
Good idea, I can take over this.

**Comment by harti2006** [comment]
@dimiro1 can you please try out version 1.4? It should contain up-to-date dependencies.

**Comment by dimiro1** [comment]
@harti2006 It worked perfectly well. Thank you guys for the super fast response.
