### ISSUE TITLE
Compatibility with Spring Boot 2.1 / Spring Cloud Greenwich

### ISSUE THREAD

**Issue by benkiefer** [zalando/spring-cloud-config-aws-kms#52]
Using the existing 3.x series with Spring Boot 2.1 results in the following error:

```
The bean 'dataSource', defined in BeanDefinition defined in class path resource 
```

The issue below sums up that you have to be on Greenwich for the two to play nicely.

https://github.com/spring-cloud/spring-cloud-config/issues/1142

**Comment by harti2006** [comment]
@benkiefer please try out version `4.0-beta1` of this library. It is based on Spring Cloud Greenwich.M3

**Comment by benkiefer** [comment]
Will do. Sorry for not getting back to you faster. Hopefully by the end of the day.

**Comment by benkiefer** [comment]
I ran into several other issues while upgrading that were unrelated to this project, but the core issue that you were trying to fix is looking good now. Thank you!

**Comment by benkiefer** [comment]
@harti2006 just wanted to share that the official release for greenwich is scheduled for next week: https://github.com/spring-cloud/spring-cloud-release/milestone/63

**Comment by harti2006** [comment]
@benkiefer as promised: Please use version 4.0 of this library together with Spring Cloud Greenwich and Spring Boot 2.1

**Comment by benkiefer** [comment]
Excellent. Thank you. We're all up to date now. Feels good. I'll enjoy the few minutes it lasts :)
