### ISSUE TITLE
No ability to set proxy information when creating kms bean

### ISSUE THREAD

**Issue by kierans** [zalando/spring-cloud-config-aws-kms#60]
I work for a corporation, and we need to set proxy information inside our Spring boot apps that use AWS resources like KMS.

When creating the `kms` bean it would be good to set proxy information if it is present in the system properties.

```
@Bean
AWSKMS kms() {
  String proxyHost = System.getProperty("http.proxyHost");
  String proxyPort = System.getProperty("http.proxyPort");

  ClientConfiguration configuration = new ClientConfiguration();
  
  if ((proxyHost != null && !proxyHost.equals("")) && (proxyPort != null && !proxyPort.equals(""))) {
    configuration.setProxyHost(proxyHost);
    configuration.setProxyPort(Integer.parseInt(proxyPort));
  }

  final AWSKMSClient awskmsClient = new AWSKMSClient(configuration);
  awskmsClient.setRegion(Region.getRegion(region));
  
  return awskmsClient;
}
```

However we're using an older version of Spring Boot (1.4.7). I can patch each of the versions of this library that correspond to the versions of Spring Boot/Spring Cloud that are supported. Can I get some guidance please?

**Comment by harti2006** [comment]
Spring Boot 1.4.X and Spring Cloud Camden are marked end-of-life. I would recommend you to upgrade to Spring Boot 1.5 and Spring Cloud Edgware?.
Anyway, since the APIs we are using here are pretty stable, I guess the version 2.X of this library should work for you.
If you like to contribute, I would suggest to create a pull request for `master-v2`. I will then help you to cherry-pick and release the feature into to the newer versions as well.

**Comment by harti2006** [comment]
Hint: Please use `PredefinedClientConfigurations#defaultConfig` to create a new instance of `ClientConfiguration` and then change the proxy settings accordingly

**Comment by kierans** [comment]
Thanks for your comments @harti2006. I inherited the project so upgrading is not something I want to attempt at this time.

**Comment by kierans** [comment]
Looking at #47 and the version of `com.amazonaws.ClientConfiguration` used in 2.X, I only need to patch the 1.X series. Are you open to creating a `master-v1` branch from `41c6fe2` and doing a 1.8 release @harti2006?

**Comment by harti2006** [comment]
@kierans thanks for reminding me of #47 - totally forgot about it 🤦‍♂️. It should definitely be mentioned in the README.
I checked out tag `1.7` and saw that it uses AWS Java SDK in version `1.11.125`. This already supports getting the proxy settings from JVM System Properties. What do you think is necessary to patch there? As far as I can see, there were only "organizational" changes compared to `41c6fe2` (see [here](https://github.com/zalando/spring-cloud-config-aws-kms/compare/1.7...41c6fe2)). So how would you benefit from 1.8?

**Comment by kierans** [comment]
Good idea putting it in the README :)

One of the issues with `1.7` is that it's using Spring Boot `1.5.x` where as my project is using `1.4.x` so I'm using version `1.5` of this library.

I'm trying another idea where I'm excluding the transitive `aws-java-sdk-kms` and forcing the use of `1.11.125`. As long as the interfaces align then `1.5` will use the version of AWSKMS that will pick up the system properties and all will be well.

**Comment by kierans** [comment]
No code fix is required. I updated my build and it all works

```
compile("org.zalando:spring-cloud-config-aws-kms:1.5") {
  exclude module: 'com.amazonaws'
}

compile "com.amazonaws:aws-java-sdk-kms:1.11.125"
```

**Comment by harti2006** [comment]
Thanks for the update 👍
