### ISSUE TITLE
Automatic region discovery

### ISSUE THREAD

**Issue by kinow** [zalando/spring-cloud-config-aws-kms#8]
Hi, the region is a required parameter for the library, but maybe instead it could

- check if the region was provided
- if not, then query the metadata server to retrieve the region
- if the metadata server returned a region, use it
- otherwise, fail

**Comment by kinow** [comment]
Perhaps check if the environment variable AWS_DEFAULT_REGION has been set as well.

**Comment by jbellmann** [comment]
@kinow 

Maybe u want to use [this spring-boot-starter](https://github.com/zalando-incubator/automata-misc/tree/master/aws-support-spring-boot-starter#aws-support-spring-boot-starter) in combination whit this one? It does not handle all your requirements/ideas but could be a starting point.

Regards
Jörg

**Comment by kinow** [comment]
It looks really interesting, I hadn't seen the project (though I saw another [interesting one](https://github.com/zalando/spring-boot-etcd) in the same repository last week).

Will take a look how hard it would be to combine both, and try to suggest in a pull request an implementation for this.

Thanks heaps
Bruno

**Comment by jbellmann** [comment]
If you are interested in more spring-boot-starters, then have a look to [this repository](https://github.com/zalando-stups/booties) as well.

**Comment by kinow** [comment]
The automatic region discovery through that spring-boot-starter worked like a charm. Had some `Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/transform/JsonErrorUnmarshallerV2`, but solved by excluding one AWS dependency.

Here's what I changed in a test project that already had this KMS library. In pom.xml:

```
+snip+
        <dependency>
            <groupId>org.zalando.automata</groupId>
            <artifactId>aws-support-spring-boot-starter</artifactId>
            <version>${aws-support-spring-boot-starter.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.amazonaws</groupId>
                    <artifactId>aws-java-sdk-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
+snip+
```

Where the version was 0.0.2.

**Comment by kinow** [comment]
Might leave this open in case we could update the README by pointing that users could either use bootstrap.yml properties, or then add a dependency to the other library.

**Comment by duergner** [comment]
Since we released the AWS Support as top level project now we should definitely point to https://github.com/zalando-incubator/aws-support-spring-boot-starter on the README
