### ISSUE TITLE
Add support to EncryptionContext

### ISSUE THREAD

**Issue by kinow** [zalando/spring-cloud-config-aws-kms#9]
I believe that at the moment I am not able to use [EncryptionContext](https://aws.amazon.com/blogs/security/how-to-protect-the-integrity-of-your-encrypted-data-by-using-aws-key-management-service-and-encryptioncontext/) with KMS and this library.

Maybe we could:

- read a property with a comma separated list of key and value pairs, containing the context
- allow users to provide a bean that would provide a map with the context

With this, users would be able to encrypt a password with some context like "environment=test", that couldn't be decrypted if "envinronment=production" or if empty. In some cases, users will have different IAM permissions, and that wouldn't happen. But when several environments have permission to encrypt/decrypt, without a context, this kind of mistake could happen. Besides, of course, increasing the application security by using the EncryptionContext.

**Comment by LappleApple** [comment]
Hi @kinow: Do you want to do this?

**Comment by kinow** [comment]
I can definitely try @LappleApple :-) returning from vacation today, so will probably submit a pull request or update this ticket in the next days.

**Comment by kinow** [comment]
Pull request submitted :-)

**Comment by harti2006** [comment]
Thank you very much @kinow 
I'm going to review it in the next days.

**Comment by kinow** [comment]
The least I could do. Not only I could use spring-cloud-config-aws-kms, which saved me (and consequently my employee) a lot of time, you guys also updated the zalando-incubator/aws-support-spring-boot-starter project :-)

**Comment by harti2006** [comment]
> which saved me (and consequently my employee) a lot of time
That's great to hear 👍

**Comment by LappleApple** [comment]
That's awesome, @kinow.

**Comment by harti2006** [comment]
@kinow your feature is merged and released in version 1.5. Should available in Maven Central in a few minutes. Thanks for your contribution. :handshake:

**Comment by kinow** [comment]
Thank you @harti2006, @LappleApple, and all others involved! Always awesome to work with Zalando. Closing the issue :tada:
